#!/bin/bash

# Getting the current username and date/time
USERNAME=$(whoami)
DATE_TIME=$(date)

# System Information
HOSTNAME=$(hostname)
OS_NAME=$(lsb_release -d | awk -F"\t" '{print $2}')
UPTIME=$(uptime -p)

# Hardware Information
CPU=$(lscpu | grep "Model name" | awk -F: '{print $2}')
RAM=$(free -h | grep "Mem:" | awk '{print $2}')
DISK_INFO=$(lsblk -d -o NAME,SIZE,MODEL | grep -v "^NAME")
VIDEO_CARD=$(lspci | grep -i vga | awk -F: '{print $2}')

# Network Information
FQDN=$(hostname -f)
HOST_IP=$(ip a | grep inet | grep -v inet6 | awk '{print $2}' | head -n 1)
GATEWAY_IP=$(ip route | grep default | awk '{print $3}')
DNS_SERVER=$(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -n 1)

# System Status
LOGGED_IN_USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')
DISK_SPACE=$(df -h | grep -E '^/dev' | awk '{print $1, $4}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average:' '{print $2}' | sed 's/ //g')
LISTENING_PORTS=$(ss -tuln | grep -E 'State|LISTEN' | awk '{print $5}' | cut -d':' -f2 | sort -u | tr '\n' ',' | sed 's/,$//')
UFW_STATUS=$(ufw status | head -n 1 | awk '{print $2}')

# Print the report
cat << EOF

System Report generated by $USERNAME, $DATE_TIME

System Information
------------------
Hostname: $HOSTNAME
OS: $OS_NAME
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
Ram: $RAM
Disk(s): $DISK_INFO
Video: $VIDEO_CARD

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_IP
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $LOGGED_IN_USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS

EOF
